export const jugadoresBrasil = [
  {
    "POS": 1,
    "Nombre": "Alisson Becker",
    "Partidos": "10",
    "Goles": "0",
    "Asistencias": "0",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "28",
    "Estatura": "1.93",
    "Peso": "91",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 2,
    "Nombre": "Danilo",
    "Partidos": "8",
    "Goles": "1",
    "Asistencias": "2",
    "Tarjetas Amarillas": "2",
    "Tarjetas Rojas": "0",
    "Edad": "29",
    "Estatura": "1.84",
    "Peso": "78",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 3,
    "Nombre": "Thiago Silva",
    "Partidos": "7",
    "Goles": "0",
    "Asistencias": "0",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "36",
    "Estatura": "1.83",
    "Peso": "79",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 4,
    "Nombre": "Marquinhos",
    "Partidos": "9",
    "Goles": "2",
    "Asistencias": "1",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "27",
    "Estatura": "1.89",
    "Peso": "83",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 7,
    "Nombre": "Lucas Paquetá",
    "Partidos": "6",
    "Goles": "3",
    "Asistencias": "2",
    "Tarjetas Amarillas": "2",
    "Tarjetas Rojas": "0",
    "Edad": "24",
    "Estatura": "1.80",
    "Peso": "72",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 8,
    "Nombre": "Fred",
    "Partidos": "9",
    "Goles": "1",
    "Asistencias": "3",
    "Tarjetas Amarillas": "3",
    "Tarjetas Rojas": "0",
    "Edad": "28",
    "Estatura": "1.69",
    "Peso": "64",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 9,
    "Nombre": "Gabriel Jesus",
    "Partidos": "10",
    "Goles": "6",
    "Asistencias": "2",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "1",
    "Edad": "24",
    "Estatura": "1.75",
    "Peso": "73",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 10,
    "Nombre": "Neymar",
    "Partidos": "8",
    "Goles": "7",
    "Asistencias": "5",
    "Tarjetas Amarillas": "3",
    "Tarjetas Rojas": "0",
    "Edad": "29",
    "Estatura": "1.75",
    "Peso": "68",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 11,
    "Nombre": "Vinícius Júnior",
    "Partidos": "5",
    "Goles": "2",
    "Asistencias": "3",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "21",
    "Estatura": "1.76",
    "Peso": "66",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 12,
    "Nombre": "Éder Militão",
    "Partidos": "7",
    "Goles": "0",
    "Asistencias": "0",
    "Tarjetas Amarillas": "2",
    "Tarjetas Rojas": "0",
    "Edad": "23",
    "Estatura": "1.86",
    "Peso": "79",
    "Nacionalidad": "Brasil",
    "Foto": ""
  },
  {
    "POS": 17,
    "Nombre": "Renan Lodi",
    "Partidos": "6",
    "Goles": "0",
    "Asistencias": "1",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "23",
    "Estatura": "1.77",
    "Peso": "70",
    "Nacionalidad": "Brasil",
    "Foto": ""
  }
];
