export const jugadores = [
    {
        "POS": 12,
        "Nombre": "Camilo Vargas",
        "Partidos": "3",
        "Goles": "0",
        "Asistencias": "1",
        "Tarjetas Amarillas": "1",
        "Tarjetas Rojas": "0",
        "Edad": "26",
        "Estatura": "1.78",
        "Peso": "68",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 4,
        "Nombre": "Santiago Arias",
        "Partidos": "5",
        "Goles": "0",
        "Asistencias": "2",
        "Tarjetas Amarillas": "0",
        "Tarjetas Rojas": "0",
        "Edad": "29",
        "Estatura": "1.69",
        "Peso": "70",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 23,
        "Nombre": "Dávinson Sánchez",
        "Partidos": "4",
        "Goles": "1",
        "Asistencias": "0",
        "Tarjetas Amarillas": "2",
        "Tarjetas Rojas": "0",
        "Edad": "23",
        "Estatura": "1.79",
        "Peso": "65",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 2,
        "Nombre": "Carlos Cuesta",
        "Partidos": "5",
        "Goles": "1",
        "Asistencias": "3",
        "Tarjetas Amarillas": "1",
        "Tarjetas Rojas": "0",
        "Edad": "24",
        "Estatura": "1.82",
        "Peso": "69",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 17,
        "Nombre": "Johan Mojica",
        "Partidos": "4",
        "Goles": "1",
        "Asistencias": "3",
        "Tarjetas Amarillas": "2",
        "Tarjetas Rojas": "0",
        "Edad": "22",
        "Estatura": "1.80",
        "Peso": "72",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 6,
        "Nombre": "Richard Rios",
        "Partidos": "3",
        "Goles": "2",
        "Asistencias": "2",
        "Tarjetas Amarillas": "2",
        "Tarjetas Rojas": "1",
        "Edad": "25",
        "Estatura": "1.76",
        "Peso": "70",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 16,
        "Nombre": "Jefferson Lerma",
        "Partidos": "4",
        "Goles": "0",
        "Asistencias": "2",
        "Tarjetas Amarillas": "0",
        "Tarjetas Rojas": "0",
        "Edad": "23",
        "Estatura": "1.69",
        "Peso": "63",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 11,
        "Nombre": "Jhon Arias",
        "Partidos": "3",
        "Goles": "1",
        "Asistencias": "1",
        "Tarjetas Amarillas": "2",
        "Tarjetas Rojas": "1",
        "Edad": "22",
        "Estatura": "1.89",
        "Peso": "78",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 10,
        "Nombre": "James Rodríguez",
        "Partidos": "5",
        "Goles": "3",
        "Asistencias": "3",
        "Tarjetas Amarillas": "1",
        "Tarjetas Rojas": "0",
        "Edad": "26",
        "Estatura": "1.65",
        "Peso": "70",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 24,
        "Nombre": "Jhon Córdoba",
        "Partidos": "4",
        "Goles": "1",
        "Asistencias": "1",
        "Tarjetas Amarillas": "1",
        "Tarjetas Rojas": "1",
        "Edad": "26",
        "Estatura": "1.80",
        "Peso": "72",
        "Nacionalidad": "Colombia",
        "Foto": ""
    },
    {
        "POS": 7,
        "Nombre": "Luis Díaz",
        "Partidos": "4",
        "Goles": "2",
        "Asistencias": "2",
        "Tarjetas Amarillas": "0",
        "Tarjetas Rojas": "0",
        "Edad": "28",
        "Estatura": "1.70",
        "Peso": "68",
        "Nacionalidad": "Colombia",
        "Foto": ""
    }
]
