export const jugadores = [
  {
    "POS": 22,
    "Nombre": "Lautaro Martínez",
    "Partidos": 6,
    "Goles": 5,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 27,
    "Estatura": "1.75 m",
    "Peso": "72 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 9,
    "Nombre": "Julián Álvarez",
    "Partidos": 5,
    "Goles": 2,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 24,
    "Estatura": "1.70 m",
    "Peso": "71 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 25,
    "Nombre": "Lisandro Martínez",
    "Partidos": 5,
    "Goles": 1,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 26,
    "Estatura": "1.75 m",
    "Peso": "72 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 10,
    "Nombre": "Lionel Messi",
    "Partidos": 5,
    "Goles": 1,
    "Asistencias": 1,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 37,
    "Estatura": "1.70 m",
    "Peso": "67 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 23,
    "Nombre": "Emiliano Martínez",
    "Partidos": 6,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 32,
    "Estatura": "1.96 m",
    "Peso": "87 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 3,
    "Nombre": "Nicolás Tagliafico",
    "Partidos": 6,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 1,
    "Tarjetas Rojas": 0,
    "Edad": 32,
    "Estatura": "1.73 m",
    "Peso": "67 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 4,
    "Nombre": "Gonzalo Montiel",
    "Partidos": 6,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 27,
    "Estatura": "1.75 m",
    "Peso": "68 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 7,
    "Nombre": "Rodrigo De Paul",
    "Partidos": 5,
    "Goles": 0,
    "Asistencias": 1,
    "Tarjetas Amarillas": 1,
    "Tarjetas Rojas": 0,
    "Edad": 30,
    "Estatura": "1.80 m",
    "Peso": "68 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 1,
    "Nombre": "Franco Armani",
    "Partidos": 0,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 38,
    "Estatura": "1.89 m",
    "Peso": "85 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 27,
    "Nombre": "Facundo Medina",
    "Partidos": 3,
    "Goles": 0,
    "Asistencias": 1,
    "Tarjetas Amarillas": 1,
    "Tarjetas Rojas": 0,
    "Edad": 24,
    "Estatura": "1.84 m",
    "Peso": "78 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 28,
    "Nombre": "Juan Foyth",
    "Partidos": 2,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 25,
    "Estatura": "1.87 m",
    "Peso": "78 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 29,
    "Nombre": "Thiago Almada",
    "Partidos": 4,
    "Goles": 1,
    "Asistencias": 1,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 22,
    "Estatura": "1.71 m",
    "Peso": "63 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 11,
    "Nombre": "Angel Di Maria",
    "Partidos": 5,
    "Goles": 3,
    "Asistencias": 2,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 35,
    "Estatura": "1.78 m",
    "Peso": "75 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 31,
    "Nombre": "Ángel Correa",
    "Partidos": 2,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 29,
    "Estatura": "1.71 m",
    "Peso": "69 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 32,
    "Nombre": "Lautaro Blanco",
    "Partidos": 1,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 25,
    "Estatura": "1.85 m",
    "Peso": "80 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 33,
    "Nombre": "Maximiliano Meza",
    "Partidos": 3,
    "Goles": 0,
    "Asistencias": 1,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 30,
    "Estatura": "1.78 m",
    "Peso": "75 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },

  {
    "POS": 34,
    "Nombre": "Nicolás González",
    "Partidos": 6,
    "Goles": 1,
    "Asistencias": 2,
    "Tarjetas Amarillas": 1,
    "Tarjetas Rojas": 0,
    "Edad": 25,
    "Estatura": "1.80 m",
    "Peso": "72 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 35,
    "Nombre": "Lucas Ocampos",
    "Partidos": 2,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 29,
    "Estatura": "1.87 m",
    "Peso": "84 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 5,
    "Nombre": "Leandro Paredes",
    "Partidos": 6,
    "Goles": 0,
    "Asistencias": 1,
    "Tarjetas Amarillas": 2,
    "Tarjetas Rojas": 0,
    "Edad": 29,
    "Estatura": "1.80 m",
    "Peso": "75 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
   {
    "POS": 24,
    "Nombre": "Enzo Fernández",
    "Partidos": 6,
    "Goles": 1,
    "Asistencias": 1,
    "Tarjetas Amarillas": 1,
    "Tarjetas Rojas": 0,
    "Edad": 23,
    "Estatura": "1.78 m",
    "Peso": "74 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 20,
    "Nombre": "Alexis Mac Allister",
    "Partidos": 7,
    "Goles": 1,
    "Asistencias": 2,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 25,
    "Estatura": "1.76 m",
    "Peso": "72 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 40,
    "Nombre": "Exequiel Palacios",
    "Partidos": 4,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 25,
    "Estatura": "1.77 m",
    "Peso": "70 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 13,
    "Nombre": "Cristian Romero",
    "Partidos": 3,
    "Goles": 0,
    "Asistencias": 1,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 25,
    "Estatura": "1.79 m",
    "Peso": "73 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 42,
    "Nombre": "Giovani Lo Celso",
    "Partidos": 1,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 27,
    "Estatura": "1.77 m",
    "Peso": "68 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  },
  {
    "POS": 43,
    "Nombre": "Alejandro Garnacho",
    "Partidos": 1,
    "Goles": 0,
    "Asistencias": 0,
    "Tarjetas Amarillas": 0,
    "Tarjetas Rojas": 0,
    "Edad": 19,
    "Estatura": "1.80 m",
    "Peso": "75 kg",
    "Nacionalidad": "Argentina",
    "Foto": ""
  }
  

];
