export const jugadoresUruguay = [
  {
    "POS": 1,
    "Nombre": "Fernando Muslera",
    "Partidos": "10",
    "Goles": "0",
    "Asistencias": "0",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "34",
    "Estatura": "1.90",
    "Peso": "84",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 3,
    "Nombre": "Diego Godín",
    "Partidos": "8",
    "Goles": "1",
    "Asistencias": "0",
    "Tarjetas Amarillas": "2",
    "Tarjetas Rojas": "0",
    "Edad": "35",
    "Estatura": "1.85",
    "Peso": "80",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 4,
    "Nombre": "José María Giménez",
    "Partidos": "9",
    "Goles": "0",
    "Asistencias": "1",
    "Tarjetas Amarillas": "2",
    "Tarjetas Rojas": "0",
    "Edad": "26",
    "Estatura": "1.85",
    "Peso": "80",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 7,
    "Nombre": "Nicolás De La Cruz",
    "Partidos": "7",
    "Goles": "2",
    "Asistencias": "2",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "24",
    "Estatura": "1.67",
    "Peso": "62",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 9,
    "Nombre": "Luis Suárez",
    "Partidos": "10",
    "Goles": "8",
    "Asistencias": "3",
    "Tarjetas Amarillas": "3",
    "Tarjetas Rojas": "1",
    "Edad": "34",
    "Estatura": "1.82",
    "Peso": "81",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 10,
    "Nombre": "Giorgian De Arrascaeta",
    "Partidos": "6",
    "Goles": "1",
    "Asistencias": "4",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "27",
    "Estatura": "1.74",
    "Peso": "70",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 11,
    "Nombre": "Darwin Núñez",
    "Partidos": "5",
    "Goles": "3",
    "Asistencias": "1",
    "Tarjetas Amarillas": "2",
    "Tarjetas Rojas": "0",
    "Edad": "22",
    "Estatura": "1.87",
    "Peso": "75",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 14,
    "Nombre": "Lucas Torreira",
    "Partidos": "7",
    "Goles": "0",
    "Asistencias": "1",
    "Tarjetas Amarillas": "2",
    "Tarjetas Rojas": "0",
    "Edad": "25",
    "Estatura": "1.68",
    "Peso": "64",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 15,
    "Nombre": "Federico Valverde",
    "Partidos": "9",
    "Goles": "1",
    "Asistencias": "3",
    "Tarjetas Amarillas": "2",
    "Tarjetas Rojas": "0",
    "Edad": "23",
    "Estatura": "1.82",
    "Peso": "78",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 17,
    "Nombre": "Matías Viña",
    "Partidos": "8",
    "Goles": "0",
    "Asistencias": "2",
    "Tarjetas Amarillas": "1",
    "Tarjetas Rojas": "0",
    "Edad": "24",
    "Estatura": "1.80",
    "Peso": "76",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  },
  {
    "POS": 19,
    "Nombre": "Sebastián Coates",
    "Partidos": "6",
    "Goles": "1",
    "Asistencias": "0",
    "Tarjetas Amarillas": "3",
    "Tarjetas Rojas": "0",
    "Edad": "30",
    "Estatura": "1.96",
    "Peso": "92",
    "Nacionalidad": "Uruguay",
    "Foto": ""
  }
];
